#!/usr/bin/env python3
import sys
sys.path.insert(0, 'f:/Uchannel/Python')
from pcad_to_autolisp import PCADParser

with open('f:/Uchannel/P-CAD-code/AutoGenerated.pcad', 'r', encoding='utf-8') as f:
    source = f.read()

parser = PCADParser(source)
parser.parse()

print('=== Sketches ===')
for sketch in parser.sketches:
    print(f"Sketch: {sketch['name']}")
    for pl in sketch['polylines']:
        print(f"  Polyline: {pl['name']} (closed={pl['closed']})")
        for i, pt in enumerate(pl['points']):
            print(f"    Point {i}: '{pt}'")
