#!/usr/bin/env python3
import sys
sys.path.insert(0, 'f:/Uchannel/Python')
from pcad_to_autolisp import PCADParser, AutoLISPGenerator

with open('f:/Uchannel/P-CAD-code/AutoGenerated.pcad', 'r', encoding='utf-8') as f:
    source = f.read()

parser = PCADParser(source)
parser.parse()

generator = AutoLISPGenerator(parser)

# Test point expressions
test_points = [
    'CulvertX, BaseH',
    'CulvertX + W, BaseH',
    'CulvertX + W, BaseH + H',
    'CulvertX, BaseH + H',
]

print('=== Point Expression Conversion ===')
for pt in test_points:
    x_expr, y_expr = generator._parse_point_expr(pt)
    print(f"Input: '{pt}'")
    print(f"  X: {x_expr}")
    print(f"  Y: {y_expr}")
    print()
