# -*- coding: utf-8 -*-
import os

def main():
    scr_path = r"H:\U形槽配筋软件\automation_temp\load_and_render.scr"
    lsp_path = r"H:/U形槽配筋软件/automation_temp/AutoGenerated.lsp"
    
    # Content of the script file
    # Note: AutoCAD paths should preferably use forward slashes to avoid escaping issues, 
    # even on Windows, or double backslashes.
    content = f'(load "{lsp_path}")\n(c:PCAD_Render)\n(command "._ZOOM" "_ALL")\n'
    
    try:
        with open(scr_path, 'w', encoding='gbk') as f:
            f.write(content)
        print(f"Successfully created {scr_path} with GBK encoding.")
    except Exception as e:
        print(f"Error creating file: {e}")

if __name__ == "__main__":
    main()
